#GetItem([])

In [1]:
import pandas as pd
import numpy as np

In [6]:

Dates = pd.date_range("20260429",periods=6)


df1 = pd.DataFrame(np.array([[1,2,4,5],[6,7,8,9],[10,11,12,13],[14,15,16,17],[18,19,20,21],[22,23,24,25]]),index=Dates,columns=list("ABCD"))
print(df1)

             A   B   C   D
2026-04-29   1   2   4   5
2026-04-30   6   7   8   9
2026-05-01  10  11  12  13
2026-05-02  14  15  16  17
2026-05-03  18  19  20  21
2026-05-04  22  23  24  25

## For a DataFrame, passing a single label selects a column and yields a Series:

In [9]:
df1["A"]

# If the label only contains letters, numbers, and underscores, you can alternatively use the column name attribute:
df1.B

2026-04-29     2
2026-04-30     7
2026-05-01    11
2026-05-02    15
2026-05-03    19
2026-05-04    23
Freq: D, Name: B, dtype: int64

In [11]:
# Passing a list of column labels selects multiple columns, which can be useful for getting a subset/rearranging:
df1[["B","A"]]

             B   A
2026-04-29   2   1
2026-04-30   7   6
2026-05-01  11  10
2026-05-02  15  14
2026-05-03  19  18
2026-05-04  23  22

In [16]:
# For a DataFrame, passing a slice : selects matching rows:
df1[0:5]

             A   B   C   D
2026-04-29   1   2   4   5
2026-04-30   6   7   8   9
2026-05-01  10  11  12  13
2026-05-02  14  15  16  17
2026-05-03  18  19  20  21

# Select by Labels

In [ ]:
print(Dates[0])
# Selecting a row matching a label:
df1.loc[Dates[0]]

2026-04-29 00:00:00

A    1
B    2
C    4
D    5
Name: 2026-04-29 00:00:00, dtype: int64

In [28]:
# Selecting all rows (:) with a select column labels:
df1.loc[:,["A","B"]]

             A   B
2026-04-29   1   2
2026-04-30   6   7
2026-05-01  10  11
2026-05-02  14  15
2026-05-03  18  19
2026-05-04  22  23

In [29]:
# For label slicing, both endpoints are included:
df1.loc["20260429":"20260501",["A","B","C"]]

             A   B   C
2026-04-29   1   2   4
2026-04-30   6   7   8
2026-05-01  10  11  12

# Selection By Position

In [33]:
# Select via the position(index) of the passed integers:

df1.iloc[0]

A    1
B    2
C    4
D    5
Name: 2026-04-29 00:00:00, dtype: int64